describe("plugin/refsearch.vim", function()
  it("defines the user commands", function()
    assert.is_true(vim.fn.exists(":RefSearch") > 0)
    assert.is_true(vim.fn.exists(":RefSearchInit") > 0)
  end)

  it("exposes the Lua API", function()
    local refsearch = require("refsearch")
    assert.is_function(refsearch.command)
    assert.is_function(refsearch.search_cursor)
    assert.is_function(refsearch.init)
  end)

  it("loads the word helper module", function()
    local word = require("refsearch.word")
    assert.is_function(word.truncate)
    assert.is_function(word.compound_noun)
  end)
end)
