name: Test

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  push:
    branches: [main]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
        neovim: [v0.11.0, v0.12.0, stable, nightly]
        luaVersion: ["luajit-openresty"]

    runs-on: ${{ matrix.os }}
    name: "OS: ${{ matrix.os }} - Neovim: ${{ matrix.neovim }}"

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Install Neovim
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: ${{ matrix.neovim }}

      - name: Install Lua
        uses: luarocks/gh-actions-lua@v13
        with:
          luaVersion: "${{ matrix.luaVersion }}"

      - name: Install LuaRocks
        uses: luarocks/gh-actions-luarocks@v7

      - name: Install Dependencies
        run: |
          luarocks install busted --local

      - name: Test
        run: |
          eval $(luarocks path --no-bin)
          busted .
